site_name: Akita Meshtastic IRC Gateway (AMIG) Documentation
site_author: Akita Engineering
site_description: Documentation for the Akita Meshtastic IRC Gateway
repo_url: https://github.com/AkitaEngineering/Akita-Meshtastic-IRC-Gateway
repo_name: AkitaEngineering/Akita-Meshtastic-IRC-Gateway
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024-2026 Akita Engineering

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md
  - User Guide:
      - Installation: usage/installation.md
      - Running the Gateway: usage/running.md
      - Connecting: usage/connecting.md
  - Commands: commands.md
  - About:
      - License: license.md
      - Contact: about/contact.md

